[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[theme]
primaryColor="#1f1f2e"
backgroundColor="#fafafb"
secondaryBackgroundColor="#f0f0f2"
textColor="#2c2c2e"